language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - chmod +x mvnw
deploy:  
  provider: heroku  
  app: app-liowl
  on:    
    branch: master
  api_key:
    secure: ${{ secrets.HEROKU_TOKEN }}