language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - chmod +x mvnw
deploy:  
  provider: heroku  
  app: app-liowl
  on:    
    branch: master
  api_key:
    secure: -----BEGIN PUBLIC KEY----- MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwCtWQA3knL4fu6x8VaW+ 3R1tFYOvg3NejFNh7k6dq+xD8MKG49ChsHd/gd/R1vJu5PH0GJTXHQVKAQQEKlWq FHoV8aDDYMdGHt0emb2prGU1EQri5Ftp/U4/P682vFUFt+SyoLaX2WmM4/GBsNj+ L0VUsoT47z8Y00UTK6GMy8S0Io4q+zrKxzY0TFBB20iYf91wmRUvLGFmp4jnLBTJ p+gi5xHUSCEoL7J4mScIEzYVW2DnwuJ0yDOrloYfQXP21pOnkXiypI1cpBa0QMGm nTMxp3TdEg3dWbxbg5X7jG/bcH+x63KzMIPvDgyU+AAaWQmqa1kIk1wxFJz/O6IK UvFEaj6h7V1Z2ZiM/27pVbre9s4LO/2sytVRT0pr37Pt5ntbXvxucUX0Rxx+s8dU pvoxh2jei3l8erc3VMVM6zSN1Qcwrs9+HaqhMByuuebP5H9DtOAFXrvksMbgyamb oU4CQbv0dr6PePcYzd0bZCwv5y4Exszirc7n7tr6uL6izosO2Nm474PhHYQFaCJO gqlV3VeE8MmAKP23xN8UpBDi/sogFpdLurVTSlpM1d/64AoB5RKS0XTUENiYUAJ9 t25i8RbuPllO5JweeMhG8FQ8HXF+i+X9/Nz57u+U2o/buB8An05aJnfDd1BRNKXy rNufG/qv2IxH1U2TgfD9Q08CAwEAAQ== -----END PUBLIC KEY-----